version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=204328232493.dkr.ecr.ap-southeast-1.amazonaws.com/devops/aws-tutorial
      - IMAGE=$REPOSITORY_URI:nginx
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $IMAGE
      - echo Writing image definitions file...
      - printf '[{"name":"AWSCodePipelineTurorial","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

